/*
 * Startup.cs
 * Main startup function.
 * Date : 2021-05-24.
 * By : Jonathan Massé
 */


// Includes.
using System;
using System.Collections.Generic;
using System.Globalization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Localization;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using RadioHLSConverter.backend.serverless.Settings;
using RadioHLSConverter.backend.serverless.Services;
using FFMpegCore;
using Microsoft.AspNetCore.Http;
using Microsoft.OpenApi.Models;


namespace RadioHLSConverter.backend.serverless
{
    /// <summary>
    /// Startup
    /// </summary>
    public class Startup
    {
        // Configuration.
        public static IConfiguration Configuration { get; private set; }


        /// <summary>
        /// Constructor.
        /// </summary>
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }


        /// <summary>
        /// ConfigureServices.
        /// This method gets called by the runtime. Use this method to add services to the container.
        /// </summary>
        public void ConfigureServices(IServiceCollection services)
        {
            ////////////////////////////////////////
            /// Add MVC & versioning.
            ////////////////////////////////////////
            services.AddMvc(options =>
                {
                    options.EnableEndpointRouting = false;
                }) // Add MVC.
                .SetCompatibilityVersion(CompatibilityVersion.Version_3_0); // NET Core version.

            ////////////////////////////////////////
            // Configure strongly typed settings objects
            ////////////////////////////////////////
            var appSettingsSection = Configuration.GetSection("AppSettings");
            services.Configure<AppSettings>(appSettingsSection);

            // Init app settings objects.
            var appSettings = new AppSettings();
            appSettingsSection.Bind(appSettings);


            ////////////////////////////////////////
            // Add languages.
            ////////////////////////////////////////
            services.AddLocalization(options => options.ResourcesPath = "Resources");
            services.Configure<RequestLocalizationOptions>(options =>
            {
                var supportedCultures = new List<CultureInfo>
                {
                    new CultureInfo("en")
                };

                options.DefaultRequestCulture = new RequestCulture("en");
                options.SupportedCultures = supportedCultures;
                options.SupportedUICultures = supportedCultures;
            });


            ////////////////////////////////////////
            // Configure DI for application services.
            ////////////////////////////////////////
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddScoped<IFFMpegConverterService, FFMpegConverterService>();
            services.AddScoped<IHLSRadioConverterService, HLSRadioConverterService>();
            services.AddScoped<IM3U8FileService, M3U8FileService>();

            GlobalFFOptions.Configure(options => options.BinaryFolder = AppDomain.CurrentDomain.BaseDirectory+ "ffmpeg-binaries");
#if DEBUG
            ////////////////////////////////////////
            // Register the Swagger generator, defining one or more Swagger documents. (API docs generator)
            // To test Swagger API go to - http://localhost:56354/swagger/
            ////////////////////////////////////////
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1.0", new OpenApiInfo{ Title = "Core API", Description = "Swagger Core API", Version = "v1.0" });

                // We must fill the textbox with Bearer before the token, like "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiI0OCIsIm5iZiI6MTU3NDk2ODk5MywiZXhwIjoxNTc1MDU1MzkzLCJpYXQiOjE1NzQ5Njg5OTN9.dmuFjfkCg6-XVbtrJT7uiUDJHcT8vqVt5pCgVM7ms2oKMu0R-t9GX0hpi7VAT5RMcnbKI-coMZq3Oe_3HSHV_Q"

                // Locate the XML file being generated by ASP.NET...
                // IMPORTANT : This part is to improve the Swagger API docs / comment.
                //var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
                //var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);

                //... and tell Swagger to use those XML comments.
                //c.IncludeXmlComments(xmlPath);
            });
#endif
        }


        /// <summary>
        /// ConfigureServices.
        /// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        /// </summary>
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
        {
            ////////////////////////////////////////
            /// Logs - initialization.
            ////////////////////////////////////////
            var logger = loggerFactory.CreateLogger(nameof(Startup));
            loggerFactory.AddFile("logs/{Date}.log");


            ////////////////////////////////////////
            // If mode is in dev, we show exception.
            ////////////////////////////////////////
            if (env.IsDevelopment())
            {
                logger.LogInformation(string.Format(Resources.Resource.startup_development_environment, GetType().Assembly.GetName().Version));
                app.UseDeveloperExceptionPage();
            }
            else
            {
                logger.LogInformation(string.Format(Resources.Resource.startup_production_environment, GetType().Assembly.GetName().Version));
                app.UseHsts();
            }


            ////////////////////////////////////////
            /// Use - initialization.
            ////////////////////////////////////////
            app.UseRequestLocalization()   // Use language.
                .UseMvc();                  // Use MVC.


            ////////////////////////////////////////
            /// Use Swagger. (API docs generator)
            /// To test Swagger API go to - http://localhost:56352/swagger/
            ////////////////////////////////////////
#if DEBUG
            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint($"/swagger/v1.0/swagger.json", "Core API");
            });
#endif
        }
    }
}