//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioHLSConverter.backend.serverless.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadioHLSConverter.backend.serverless.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, invalid m3u8 file url.
        /// </summary>
        public static string error_invalid_m3u8_file_url {
            get {
                return ResourceManager.GetString("error_invalid_m3u8_file_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, invalid m3u8 format!.
        /// </summary>
        public static string error_invalid_m3u8_format {
            get {
                return ResourceManager.GetString("error_invalid_m3u8_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, cannot load first segment, please check buffer length configuration!.
        /// </summary>
        public static string error_no_first_segment_check_buffer {
            get {
                return ResourceManager.GetString("error_no_first_segment_check_buffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, no stream found!.
        /// </summary>
        public static string error_no_stream_found {
            get {
                return ResourceManager.GetString("error_no_stream_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, radio id not found!.
        /// </summary>
        public static string error_radio_id_not_found {
            get {
                return ResourceManager.GetString("error_radio_id_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected client, GetRadio - IP : {0} - Radio ID : {1} - Radio Name : {2}.
        /// </summary>
        public static string radio_connected_client {
            get {
                return ResourceManager.GetString("radio_connected_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected client - {0}, GetRadio - IP : {1} - Radio ID : {2} - Radio Name : {3}.
        /// </summary>
        public static string radio_disconnected_client {
            get {
                return ResourceManager.GetString("radio_disconnected_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In development environment!.
        /// </summary>
        public static string startup_development_environment {
            get {
                return ResourceManager.GetString("startup_development_environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In production environment!.
        /// </summary>
        public static string startup_production_environment {
            get {
                return ResourceManager.GetString("startup_production_environment", resourceCulture);
            }
        }
    }
}
